language: rust
rust:
- nightly
env:
  global:
  - secure: "FmkyMc5RIU2m+VZoRwuUQy/pupXrSPXAz53B+xlkbmTXDjKXrlQpRGthz3tuc24rZkhVgFdJQNLoV5kJZdyYiz5v+Nj6WcFazwgvHfkLcT+Ayjo9qd5faE6QaijBl9fDLVJIIBj0DiKPOxo9iFh2QE9Ag/5HWYsdlk20n6h7xbVh8OAAx/+sf3XuA9/vGUqVP48IGu7/QpksD+6HlroNA2zQB473rMnG6zm1s7GjWY+HyGZ+obvNta73t1rpFabuAZ3lUQOl7KDpnvZq64PqPwAV4C1sWH9g+MuIPVAoA3AOUVWJfPO2hKW+AG6L1YTNV/XeDVysTwNi4KyZk/g8QViJZi8HlxgrLHCAjLUsMhN19nmTvYUrxCKn78FGtfjS53NIvoGgVE+C34n52/hbcpdjJEg3lsVlRCPA1DZR1PK8SaYok48fYtN+9hYhg5ghP2+xY3zPaGAJ39cCGw/JNrAreIJUY36t2yaz00SnB377KAjvzzs/OW6dkY+yOjGHoWuFS4AyOeCPZ+2hebcObQGbIMC/4+rZLk28KzkVWNBgXLFG2+D+m5PfpbPlLNxJjn69pgMOJaTJXqtCa6iI4XFH4gxVHT/YKHA1BrzTALp1BZ6opzcvOwPI8jjNy1H+woKhRdXydTWMtud6CP8NM3E+V0V+kJ75rk2KGoYuVYM="
  - secure: "DSNhctCv0LAlUUIZQIpiO35SlBXB+LPKWZGaJuZIjIi3s+Reqx1vcf9fRXiJPNUuxcqJ2NSxvWZQZG9hwlabx9hshYyNQvbA+GBn1D2Kwg8Pdx6XAmfp/2fce4/sKMv+Zw/I4qdd7P9f0gzp95/YZhY8d1/MCsGwB36wKApVjW0/FtvCIitssY/o9wXMncN8L0MDdySi1Jxr/Abb7TRCnJuPExeD6+/j8Y8U2vbUUb2tvMbwryAUQIYw0fqgEXvQ+t5qodAYLyiG2a0Eh/EGSLtYlc8YDyJNjzSyuo96Zwl+AZGP0hjOv44nLOgbd2E7r1dVkXKSJeV0MvFUs8QcAKit6I21RzQb9kuFVMpev9F56+/EP5mzRtqczr+lUo1yQZ36W3wOTx/T8kPIJ8TgQxrsSq5Q7l3XpshuLZBGc+FVJb4qXedKLESRebVmSRXaJPr0EXjrw4vuCZqCX/e6+vch/RR5JBVfQ4oqXzc5Cbqjt3axLMcG7evpHk8CxPacTqcWswcguEXQGPfyOa4Ua83dsaZokJ7YfuNOezdnZSp0+S7vJjRGqhNkM6GiWydpqcRbrifz0QmggyxnqnxBYbolfqJSFZg1Y3PfD3c/LvufD/Ik7IDduBhEHNIi5EIcG9l9+Id4nKLu1/7CA7PE7zVGOg45f61Hz9TuUfIrcJo="
before_install:
- openssl aes-256-cbc -K $encrypted_56c9f8f9c907_key -iv $encrypted_56c9f8f9c907_iv
  -in .travis/dokku-deploy.key.enc -out .travis/dokku-deploy.key -d
- chmod +x .travis/deploy.sh
after_success:
- |
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    bash .travis/deploy.sh;
  fi;
